language: rust

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
          env: RUNCMD="cargo test"
        - rust: beta
          env: RUNCMD="cargo test"
        - rust: nightly
          env: RUNCMD="cargo test --features clippy"
        - os: osx
          rust: stable
          env: RUNCMD="cargo test"

sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - $RUNCMD

notifications:
  email: false
