language: rust

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
        - os: osx
          rust: stable
        - rust: beta
        - rust: nightly

sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo build --features clippy ; else cargo build ; fi'
  - cargo test --verbose

notifications:
  email: false
