[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "a msgpack-rpc client and server based on tokio"
homepage = "https://github.com/little-dude/rmp-rpc"
keywords = [
    "msgpack",
    "rpc",
    "msgpack-rpc",
]
license-file = "LICENSE-MIT"
name = "rmp-rpc"
readme = "README.md"
repository = "https://github.com/little-dude/rmp-rpc"
version = "0.1.0"

[features]
default = ["tls"]
tls = ["native-tls", "tokio-tls"]

[dependencies]
bytes = "0.4.6"
futures = "0.1.17"
log = "0.4.1"
rmpv = "0.4.0"
tokio-core = "0.1.12"
tokio-io = "0.1.4"

[dependencies.clippy]
optional = true
version = "0.0.179"

[dependencies.native-tls]
optional = true
version = "0.1.5"

[dependencies.tokio-tls]
optional = true
version = "0.1.4"

[dev-dependencies]
env_logger = "0.4.3"
