[package]
name = "rmp-rpc"
version = "0.0.5"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "a msgpack-rpc client and server based on tokio"
homepage = "https://github.com/little-dude/rmp-rpc"
repository = "https://github.com/little-dude/rmp-rpc"
readme = "README.md"
keywords = ["msgpack", "rpc", "msgpack-rpc"]
license-file = "LICENSE-MIT"

[dependencies]
rmpv = ""
rmp = "*"
bytes = "*"
futures = "*"
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
futures-cpupool = "*"
clippy = {version = ">=0.0, <0.1", optional = true}
