[package]
name = "rmp-rpc"
version = "0.0.7"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "a msgpack-rpc client and server based on tokio"
homepage = "https://github.com/little-dude/rmp-rpc"
repository = "https://github.com/little-dude/rmp-rpc"
readme = "README.md"
keywords = ["msgpack", "rpc", "msgpack-rpc"]
license-file = "LICENSE-MIT"

[dependencies]
bytes = "0.4"
env_logger = "0.4"
futures = "0.1"
log = "0.3"
rmp = "0.8"
rmpv = "0.4"
tokio-core = "0.1"
tokio-io = "0.1"

clippy = {version = ">=0.0, <0.1", optional = true}
