[package]
name = "calculator-example"
version = "0.0.1"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "a simple calculator msgpack-rpc server and client"

[dependencies]
rmp-rpc = { path = "../.." }
futures = "*"
tokio-core = "*"
rmpv = "*"
