[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "a simple calculator msgpack-rpc server and client"
name = "calculator-example"
version = "0.0.1"

[dependencies]
futures = "0.1.15"
rmpv = "0.4.0"
tokio-core = "0.1.9"

[dependencies.rmp-rpc]
path = "../.."
